# Generated by Django 6.0.7 on 2026-08-06 14:29

import django.db.models.deletion
import pets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_code",
                    models.CharField(
                        default=pets.models.generate_public_code,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[("dog", "Perro"), ("cat", "Gato"), ("other", "Otro")],
                        default="dog",
                        max_length=10,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Macho"), ("female", "Hembra")],
                        max_length=6,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=50)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="pets/")),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_phone_alt", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("vaccines_ok", models.BooleanField(default=False)),
                ("neutered", models.BooleanField(default=False)),
                ("allergies", models.TextField(blank=True)),
                ("medical_conditions", models.TextField(blank=True)),
                ("vet_name", models.CharField(blank=True, max_length=150)),
                ("vet_phone", models.CharField(blank=True, max_length=20)),
                ("is_lost", models.BooleanField(default=False)),
                ("last_seen_location", models.CharField(blank=True, max_length=200)),
                ("last_seen_date", models.DateField(blank=True, null=True)),
                ("reward", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de aprobación"),
                            ("approved", "Aprobado / Publicado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
