# Generated by Django 6.0.7 on 2026-08-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_pet_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="clinical_notes",
            field=models.TextField(
                blank=True,
                help_text="Actualizaciones recientes: cirugías, tratamientos en curso, cambios de peso, etc.",
                verbose_name="Novedades clínicas",
            ),
        ),
    ]
