# Generated by Django 6.0.7 on 2026-08-12 21:22

import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_medicalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="medical_access_code",
            field=models.CharField(
                blank=True,
                default=pets.models.generate_medical_code,
                editable=False,
                max_length=6,
            ),
        ),
    ]
