# Generated by Django 6.0.7 on 2026-08-13 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_pet_alter_order_plan'),
        ('pets', '0005_pet_medical_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='clinical_history_enabled',
            field=models.BooleanField(default=True, verbose_name='Historia clínica habilitada'),
        ),
        migrations.AddField(
            model_name='pet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='orders.order'),
        ),
    ]
