# Generated by Django 6.0.7 on 2026-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_pet_clinical_history_enabled_pet_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="renewal_due_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Vencimiento del mantenimiento anual",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="subscription_active",
            field=models.BooleanField(default=True, verbose_name="Suscripción activa"),
        ),
    ]
