# Generated by Django 6.0.7 on 2026-08-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0007_pet_renewal_due_date_pet_subscription_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="renewal_reminder_sent",
            field=models.BooleanField(
                default=False, verbose_name="Recordatorio de renovación enviado"
            ),
        ),
    ]
