# Generated by Django 6.0.7 on 2026-08-06 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("classic", "Clásica"),
                            ("family", "Familiar"),
                            ("premium", "Premium"),
                        ],
                        default="classic",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "production_status",
                    models.CharField(
                        choices=[
                            ("waiting", "En espera"),
                            ("in_production", "En producción"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregado"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="pets.pet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
