# Generated by Django 6.0.7 on 2026-08-13 00:29

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("pets", "0005_pet_medical_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(
                default=orders.models.generate_order_reference,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pet",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="pets.pet",
            ),
        ),
    ]
