# Generated by Django 6.0.7 on 2026-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_reference_alter_order_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pet',
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.CharField(choices=[('classic', 'Básico'), ('premium', 'Premium'), ('family', 'Familiar')], default='classic', max_length=10),
        ),
    ]
