# Generated by Django 6.0.7 on 2026-08-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_pet_alter_order_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Dirección de envío"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Número de guía"
            ),
        ),
    ]
